### ISSUE TITLE
Crash with BakedModed when breaking it (in survival) and hardness isn't 0.

### ISSUE THREAD

**Issue by Da-Technomancer** [McJty/ModTutorials#3] opened 2016-06-17 19:35 UTC
Basically the title, if I follow the baked model block tutorial exactly, in fact if I download the source code and compile it, it works fine when you can instabreak the ISBM blocks. But if I set the block hardness to something other than 0 and try to break it in survival, the game crashes because the baked model can't handle the breaking animation. How do I fix this?

**Comment by McJty** [comment] 2016-08-09 14:28
Sorry haven't checked into this. I'll try to check it out soon

**Comment by Da-Technomancer** [comment] 2016-08-09 21:12
I also forgot to put this into the issue at the time, but the ISBM blocks also render extremely dark in certain chunks (3d chunks, 16x16x16), with the chunks it renders incredibly dark in changing seemingly randomly with every re-log. I haven't been able to solve that one at all. 

With the crash on breaking the blocks though, I found the problem, when breaking the block the extendedBlockState doesn't have the property-values so adding:

if(extendedBlockState.getValue(Properties.CONNECT) == null){
	return Collections.emptyList();
}
 into getQuads fixed it.

**Comment by McJty** [comment] 2016-08-10 10:12
Well I cannot actually reproduce the problem. Before I apply your fix I would like to understand why it is needed. I set the hardness to 1.0f but it works fine for me (breaking the block with a pickaxe I mean). What do you do to reproduce this and what version of forge are you using?

**Comment by Da-Technomancer** [comment] 2016-08-10 11:33
I had the problem with forge-1.10.2-12.18.0.2005, and I was also using hardness of 1.0f. It was occurring for me that the moment it starts displaying the breaking texture it crashed, Other than that, you seem to be doing the same thing as I was.

**Comment by McJty** [comment] 2016-08-10 12:39
Hmm, that's already a very old version of forge. I recommend updating because I think the bug is gone in forge

**Comment by Da-Technomancer** [comment] 2016-08-10 14:10
I just looked at the forge changelog, and it looks like it was recently fixed.

Build 1.10.2-12.18.1.2046:
	AlgorithmX2:
		Fix Vertex Transformer for breaking models (#3132)
		* Add setTexture to IVertexConsumer and propagate it.

**Closed** 2017-03-26 23:26 UTC
